### PR TITLE
Increase max search results length from 5000 to 10000

### LINKED ISSUE #73: Retrieving records more than 5000 records
Currently the Search API Endpoint `https://api-docs.npms.io/` only allows a maximum of **5250** records with its `from` and `size` parameters. Is there an authenticated way to retrieve more records using the `search` endpoint

### PR DESCRIPTION
**Pull request by kategengler**
Fixes #73

### CODE REVIEW

**Comment by satazor** [comment]
Thanks, will deploy tomorrow morning!

**Comment by kategengler** [comment]
Great, thanks!

**Comment by kategengler** [comment]
@satazor Were you able to deploy this? 

`https://api.npms.io/v2/search?q=keywords:ember-addon&size=250&from=5250` still gives me an invalid parameter error for `from`

**Comment by satazor** [comment]
I've forgotten 🙈

Should be deployed now, can you confirm?

**Comment by kategengler** [comment]
Yes it is! Thanks for the super-fast response 😃

**Pull request merged**
